global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

log:
  level: INFO

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
  file:
    filename: "/etc/traefik/traefik_dynamic_conf.yml"

certificatesResolvers:
  letsencrypt_staging:
    acme:
      email: "your_email"
      storage: "/etc/traefik/acme/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: {}
  letsencrypt:
    acme:
      email: "your_email"
      storage: "/etc/traefik/acme/acme.json"
      tlsChallenge: {}
