logLevel = "INFO"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$S5b35Edt$Pu4zAw66yrRRDIoOKlejV/"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      ]

[api]
entrypoint="dashboard"

[accessLog]
filePath = "/var/log/access.log"

[acme]
email = "{{ YOUR_EMAIL }}"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
# Staging Let's Encrypt server for test purpose :
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.tlsChallenge]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "{{ YOUR_DOMAIN }}"
watch = true
exposedbydefault = false
